### ISSUE TITLE
Checklist of Scrutinizer issues

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/advancedpolls#47]
We will ignore the ACP things for now, I will rework that.
There are some issues in `core\advancedpolls.php` though:

[Scrutinizer Issues - core\advancedpolls.php](https://scrutinizer-ci.com/g/Wolfsblvt/advancedpolls/issues/master/files/core/advancedpolls.php)

- [x] The parameter `$poll` is not used and could be removed.
- [x] The variable $post_data does not exist. Did you forget to declare it?
- [x] It seems like you are calling the size function count() as part of the test condition (Note: Do "$i = 0, $count = count(....) in the declaration part)
- [x] Travis Error: Line 91 | ERROR | Whitespace found at end of line ([Link](https://travis-ci.org/Wolfsblvt/advancedpolls/jobs/61679874))

@javiexin Can you fix those issues in an additional branch? Should be fast to do, and maybe you will learn something there :P

**Comment by javiexin** [comment]
I'll work on them.  At first glance, 1 & 2 are actually the same, most probably introduced in the rebase.
And 3 is easy enough to change.  This is my fault, as this construct (using count() in the expression) in other languages is in fact more performant than creating an extra var...

**Comment by Wolfsblvt** [comment]
Okay, great.
Yeah, PHP has some stuff you just have to learn. Like the assign stuff, I didn't know it as well since Scrutinizer told me for the first time :D 
I have added a fourth point, Error in Travis, wich should be even more easy to fix.

**Comment by javiexin** [comment]
Commit with all fixes done.
